# Generated by Django 5.1.2 on 2025-01-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='userpic',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/', verbose_name='фото'),
        ),
    ]
