# Generated by Django 5.1.2 on 2025-02-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_buyer_userpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='overviev',
            field=models.TextField(blank=True, max_length='1000', verbose_name='Описание продавца'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='userpic',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='фото'),
        ),
    ]
