# Generated by Django 5.1.7 on 2025-03-11 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='Fromuser',
        ),
        migrations.AddField(
            model_name='comment',
            name='recepiend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments_received', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
