# Generated by Django 5.1.7 on 2025-03-11 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_user_comment_fromuser_comment_recepiend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Fromuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_fromUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
