# Generated by Django 5.1.7 on 2025-03-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_comment_fromuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(default=1, verbose_name='ИД поста'),
        ),
    ]
